In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

In [76]:
df = pd.read_csv('prediction_price.csv')
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")
pd.set_option('display.max_columns', None)
df.head(10)

,state,city,street,zipcode,bedroom,bathroom,area,ppsq,lotarea,marketestimate,rentestimate,latitude,longitude,listedprice
0,AL,Saraland,Scott Dr,36571.0,4.0,2.0,1614.0,148.636927,0.380500,240600.0,1599.0,30.819534,-88.095960,239900.0
1,AL,Robertsdale,Cowpen Creek Rd,36567.0,3.0,2.0,1800.0,144.388889,3.200000,NaN,NaN,30.590004,-87.580376,259900.0
2,AL,Gulf Shores,Spinnaker Dr #201,36542.0,2.0,2.0,1250.0,274.000000,NaN,NaN,NaN,30.284956,-87.747920,342500.0
3,AL,Chelsea,Mallet Way,35043.0,3.0,3.0,2224.0,150.629496,0.260000,336200.0,1932.0,33.357986,-86.608700,335000.0
4,AL,Huntsville,Turtlebrook Ct,35811.0,3.0,2.0,1225.0,204.081633,NaN,222700.0,1679.0,34.775517,-86.440700,250000.0
5,AL,Montgomery,Brampton Ln,36117.0,3.0,2.0,1564.0,96.547315,0.200000,150500.0,1385.0,32.372746,-86.165115,151000.0
6,AL,Boaz,Greenwood Ave,35957.0,3.0,2.0,1717.0,139.196273,0.380000,238400.0,2125.0,34.210014,-86.136690,239000.0
7,AL,Albertville,Lexington Ave,35950.0,3.0,2.0,1674.0,149.283154,0.344353,248000.0,1597.0,34.275400,-86.217920,249900.0
8,AL,Mobile,Emerald Dr W,36619.0,3.0,3.0,2190.0,134.703196,0.344300,294000.0,1900.0,30.595074,-88.203070,295000.0
9,AL,Madison,Highpointb Plan Grayson Lndg,35756.0,4.0,3.0,3030.0,173.234323,0.340000,NaN,NaN,34.755985,-86.865920,524900.0

### Understanding Data

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22681 entries, 0 to 22680
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   state           22681 non-null  object
 1   city            22681 non-null  object
 2   street          22681 non-null  object
 3   zipcode         22681 non-null  float64
 4   bedroom         22667 non-null  float64
 5   bathroom        22647 non-null  float64
 6   area            22681 non-null  float64
 7   ppsq            22681 non-null  float64
 8   lotarea         21779 non-null  float64
 9   marketestimate  15445 non-null  float64
 10  rentestimate    16705 non-null  float64
 11  latitude        22681 non-null  float64
 12  longitude       22681 non-null  float64
 13  listedprice     22681 non-null  float64
dtypes: float64(11), object(3)
memory usage: 2.4+ MB

In [78]:
df.isna().sum()

state                0
city                 0
street               0
zipcode              0
bedroom             14
bathroom            34
area                 0
ppsq                 0
lotarea            902
marketestimate    7236
rentestimate      5976
latitude             0
longitude            0
listedprice          0
dtype: int64

In [79]:
((df.isnull().sum()/len(df))*100).sort_values(ascending=False)

marketestimate    31.903355
rentestimate      26.348045
lotarea            3.976897
bathroom           0.149905
bedroom            0.061726
city               0.000000
street             0.000000
zipcode            0.000000
state              0.000000
ppsq               0.000000
area               0.000000
latitude           0.000000
longitude          0.000000
listedprice        0.000000
dtype: float64

In [80]:
df.describe()

,zipcode,bedroom,bathroom,area,ppsq,lotarea,marketestimate,rentestimate,latitude,longitude,listedprice
count,22681.000000,22667.000000,22647.000000,22681.000000,22681.000000,21779.000000,1.544500e+04,16705.000000,22681.000000,22681.000000,2.268100e+04
mean,50023.455403,3.393435,2.423299,2128.138398,222.641994,2.354870,4.870383e+05,2624.699192,39.751686,-92.299353,5.324399e+05
std,29570.312497,1.050506,1.157670,1577.512556,202.811788,16.128371,1.155986e+06,4029.614920,5.694751,16.866820,1.574922e+06
min,1002.000000,0.000000,0.000000,120.000000,1.925926,0.000000,1.570000e+04,100.000000,25.449816,-161.772780,4.888000e+03
25%,25419.000000,3.000000,2.000000,1400.000000,132.729544,0.173439,2.306000e+05,1641.000000,35.938618,-103.317760,2.250000e+05
50%,50703.000000,3.000000,2.000000,1849.000000,184.122149,0.299449,3.417000e+05,2149.000000,39.938480,-89.185210,3.449000e+05
75%,74134.000000,4.000000,3.000000,2466.000000,257.118205,0.930000,4.995000e+05,2800.000000,42.936455,-79.108376,4.999000e+05
max,99950.000000,21.000000,25.000000,99990.000000,6117.071334,800.000000,7.195920e+07,212834.000000,65.044370,-67.016030,7.600000e+07

In [81]:
df.describe(include='object')

        state     city   street
count   22681    22681    22681
unique     49     5481    19315
top        CT  Lincoln  Main St
freq      499      237       44

In [82]:
df.duplicated().sum()

np.int64(0)

### Data Cleaning

In [83]:
for col in df.select_dtypes(include=object).columns.tolist():
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-'*50)

state
49
['AL' 'AK' 'AZ' 'AR' 'OK' 'MO' 'CA' 'CO' 'CT' 'OH' 'DE' 'FL' 'GA' 'ID'
 'MT' 'IL' 'IN' 'IA' 'KS' 'KY' 'LA' 'ME' 'MD' 'MA' 'MI' 'MN' 'MS' 'NE'
 'NV' 'NH' 'NJ' 'NM' 'NY' 'NC' 'ND' 'OR' 'PA' 'RI' 'SC' 'SD' 'TN' 'TX'
 'UT' 'VT' 'VA' 'WA' 'WV' 'WI' 'WY']
--------------------------------------------------
city
5481
['Saraland' 'Robertsdale' 'Gulf Shores' ... 'Granite Canon' 'Shoshoni'
 'Mills']
--------------------------------------------------
street
19315
['Scott Dr' 'Cowpen Creek Rd' 'Spinnaker Dr #201' ... 'Bar Two Dr'
 'Road 210a' 'Mason Dr']
--------------------------------------------------

In [84]:
for col in df.select_dtypes(exclude=object).columns.tolist():
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-'*50)

zipcode
9264
[36571. 36567. 36542. ... 82649. 83112. 82932.]
--------------------------------------------------
bedroom
18
[ 4.  3.  2.  5.  6.  8.  1.  7.  0.  9. nan 14. 10. 13. 16. 21. 11. 12.
 18.]
--------------------------------------------------
bathroom
33
[ 2.          3.          1.          4.          5.          6.
  0.          8.          3.5         2.5         1.75        2.75
  2.25        7.          4.5         5.5        10.          9.
 11.         12.                 nan  1.5         0.75       13.
 17.         25.         14.         23.          3.0999999   2.0999999
  1.10000002  4.0999999   2.20000005  1.20000005]
--------------------------------------------------
area
4072
[ 1614.  1800.  1250. ...  9260.  4771. 10041.]
--------------------------------------------------
ppsq
20604
[148.63692689 144.38888889 274.         ... 241.80194805 196.55290102
 143.43478261]
--------------------------------------------------
lotarea
5546
[0.3805     3.2               nan ... 0.1828     0.48429752 9.36      ]
--------------------------------------------------
marketestimate
6860
[240600.     nan 336200. ... 326800. 466800. 193400.]
--------------------------------------------------
rentestimate
3313
[ 1599.    nan  1932. ...  3818. 11856.  4777.]
--------------------------------------------------
latitude
22609
[30.819534 30.590004 30.284956 ... 43.52164  41.13845  42.86544 ]
--------------------------------------------------
longitude
22601
[ -88.09596   -87.580376  -87.74792  ... -109.59405  -105.05279
 -106.27745 ]
--------------------------------------------------
listedprice
2776
[ 239900.  259900.  342500. ...  191000. 3680000.  575900.]
--------------------------------------------------

In [85]:

df[df['lotarea'] == 0]

,state,city,street,zipcode,bedroom,bathroom,area,ppsq,lotarea,marketestimate,rentestimate,latitude,longitude,listedprice
74,AL,Birmingham,3rd St S,35205.0,2.0,2.0,778.0,170.951157,0.0,NaN,NaN,33.498814,-86.828170,133000.0
82,AL,Dothan,Meadowbrook Dr,36303.0,3.0,2.0,1664.0,105.168269,0.0,165000.0,1435.0,31.240427,-85.434040,175000.0
125,AL,Homewood,Sandner Ct APT D,35209.0,2.0,1.0,864.0,219.907407,0.0,NaN,NaN,33.471996,-86.786545,190000.0
170,AL,Birmingham,11th Ave S APT 202,35205.0,2.0,2.0,1566.0,214.495530,0.0,NaN,NaN,33.504580,-86.785140,335900.0
187,AL,Birmingham,Chase Ln #3015,35215.0,1.0,1.0,741.0,80.836707,0.0,58500.0,741.0,33.661690,-86.679050,59900.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22253,WY,Cheyenne,E Prosser Rd LOT 10,82007.0,3.0,2.0,1188.0,71.548822,0.0,82800.0,356.0,41.107290,-104.796830,85000.0
22524,WY,Rozet,State Highway 51,82727.0,3.0,2.0,2100.0,66.619048,0.0,133500.0,1800.0,44.285380,-105.490370,139900.0
22553,WY,Cheyenne,Secret Valley Trl,82007.0,3.0,2.0,1280.0,67.968750,0.0,83400.0,271.0,41.076460,-104.806320,87000.0
22654,WY,Casper,E 21st St,82609.0,3.0,3.0,1800.0,202.777778,0.0,354600.0,1724.0,42.830086,-106.261370,365000.0
22672,WY,Jackson,S Glenwood St #304,83001.0,3.0,3.0,1729.0,2128.397918,0.0,NaN,NaN,43.477757,-110.764040,3680000.0

In [86]:
df[df['bathroom'] == 0]

,state,city,street,zipcode,bedroom,bathroom,area,ppsq,lotarea,marketestimate,rentestimate,latitude,longitude,listedprice
504,AK,Indian,Seward Hwy,99587.0,1.0,0.0,1250.0,159.920000,4.990000,NaN,4407.0,60.862892,-149.015560,199900.0
555,AK,Fairbanks,Old Wood Rd,99709.0,1.0,0.0,400.0,312.250000,6.700000,121300.0,1250.0,64.840610,-148.058850,124900.0
602,AK,Fairbanks,Pedro Dome Rd,99712.0,0.0,0.0,450.0,133.111111,1.100000,55000.0,1250.0,65.044370,-147.450780,59900.0
685,AK,Soldotna,Sandy Cir,99669.0,1.0,0.0,576.0,173.437500,2.300000,91600.0,1262.0,60.513890,-150.775970,99900.0
734,AK,Sutton,W Nancy Ln,99674.0,1.0,0.0,768.0,130.208333,1.400000,98700.0,3200.0,61.793950,-147.746100,100000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21966,WI,Hurley,Shea Rd,54534.0,2.0,0.0,358.0,362.849162,0.321258,NaN,NaN,46.257824,-90.134970,129900.0
22069,WI,Alvin,River Bank Ln,54542.0,0.0,0.0,320.0,234.375000,0.489991,NaN,NaN,46.029110,-88.837680,75000.0
22272,WY,Pinedale,Iron Shirt Ln,82941.0,1.0,0.0,450.0,322.222222,3.210000,143300.0,2550.0,43.031906,-110.088350,145000.0
22288,WY,Daniel,Beaver Ridge Rd,83115.0,1.0,0.0,350.0,400.000000,10.060000,NaN,1999.0,42.971222,-110.315216,140000.0
22300,WY,Pinedale,Sylvan Ln,82941.0,0.0,0.0,320.0,467.187500,NaN,NaN,394.0,42.951412,-109.777370,149500.0

In [87]:
df[df['bedroom'] == 0]

,state,city,street,zipcode,bedroom,bathroom,area,ppsq,lotarea,marketestimate,rentestimate,latitude,longitude,listedprice
602,AK,Fairbanks,Pedro Dome Rd,99712.0,0.0,0.0,450.0,133.111111,1.100000,55000.0,1250.0,65.044370,-147.450780,59900.0
817,AK,Sterling,Real Property,99672.0,0.0,0.0,416.0,115.384615,0.000000,48000.0,1452.0,60.536010,-150.794330,48000.0
869,AK,Kasilof,Squirrel St,99610.0,0.0,1.0,864.0,127.893519,0.930000,109800.0,1385.0,60.260372,-151.280380,110500.0
6332,IA,Des Moines,Shaw St,50309.0,0.0,0.0,1420.0,56.338028,0.227000,77600.0,1614.0,41.581150,-93.602510,80000.0
8303,ME,East Baldwin,Bridgton Road,4024.0,0.0,2.0,3038.0,36.175115,0.250000,118100.0,1999.0,43.844776,-70.673030,109900.0
8869,MD,Baltimore,McCulloh St,21217.0,0.0,0.0,1350.0,14.814815,NaN,NaN,1700.0,39.309450,-76.635910,20000.0
8879,MD,Baltimore,Westmont Ave,21216.0,0.0,0.0,1320.0,53.030303,0.030000,67900.0,1599.0,39.300700,-76.671250,70000.0
8949,MD,North East,Red Toad Rd,21901.0,0.0,0.0,912.0,137.061404,0.309894,NaN,NaN,39.607320,-75.975630,125000.0
8956,MD,Baltimore,N Morley St,21229.0,0.0,0.0,1041.0,19.212296,0.033425,82500.0,1350.0,39.287420,-76.673100,20000.0
9395,MA,Boston,Commercial St,2109.0,0.0,1.0,500.0,300.000000,0.000000,NaN,NaN,42.367146,-71.053000,150000.0
10016,MI,Prescott,John St,48756.0,0.0,0.0,320.0,109.062500,0.190000,NaN,1250.0,44.215237,-84.034360,34900.0
10458,MN,Sturgeon Lake,Thornbury Way,55783.0,0.0,1.0,755.0,185.298013,0.459137,NaN,NaN,46.358387,-92.750870,139900.0
10784,MS,Diamondhead,Lakeside Villa #A,39525.0,0.0,1.0,471.0,166.666667,0.010000,75800.0,885.0,30.389992,-89.358665,78500.0
12194,NE,Columbus,Old Lodge Rd,68601.0,0.0,1.0,693.0,186.147186,NaN,126200.0,1074.0,41.362534,-97.485310,129000.0
12235,NE,Oneill,S 6th St,68763.0,0.0,3.0,816.0,76.593137,NaN,NaN,900.0,42.456960,-98.644325,62500.0
12269,NE,Oneill,E Everett St,68763.0,0.0,3.0,968.0,64.566116,NaN,NaN,1094.0,42.456680,-98.644356,62500.0
12551,NV,Las Vegas,E Harmon Ave APT 112,89169.0,0.0,1.0,621.0,247.987118,NaN,179000.0,1199.0,36.107635,-115.162790,154000.0
12804,NV,Las Vegas,S Fort Apache Rd UNIT 2068,89117.0,0.0,1.0,752.0,280.585106,0.303000,210200.0,1294.0,36.145250,-115.294320,211000.0
13314,NH,Hampton,Ocean Boulevard UNIT 3,3842.0,0.0,1.0,216.0,693.981481,NaN,NaN,NaN,42.921120,-70.798970,149900.0
13698,NM,El Prado,Ovejeros Rd,87529.0,0.0,1.0,600.0,458.333333,1.990000,273800.0,1350.0,36.464270,-105.616380,275000.0
15130,ND,Beach,3rd Ave SE,58621.0,0.0,2.0,3314.0,19.010260,0.290000,69900.0,2294.0,46.913760,-104.001920,63000.0
16147,OK,Lindsay,S Main St,73052.0,0.0,1.0,1975.0,48.101266,0.085973,NaN,NaN,34.836533,-97.603110,95000.0
16510,OR,Bend,Pintail Dr,97707.0,0.0,0.0,768.0,488.281250,0.900000,351500.0,1700.0,43.821598,-121.464264,375000.0
16549,OR,Idanha,Marion Creek Rd,97350.0,0.0,1.0,1200.0,116.666667,0.300000,139200.0,1489.0,44.695900,-121.993500,140000.0
20104,VT,Stowe,South Main Street,5672.0,0.0,2.0,1496.0,467.245989,0.500000,730600.0,2550.0,44.457123,-72.694020,699000.0
20580,VA,Elkton,Jollett Rd,22827.0,0.0,1.0,1104.0,99.547101,0.390000,NaN,NaN,38.464535,-78.521150,109900.0
20979,WA,Snoqualmie Pass,Denny Creek Road,98068.0,0.0,1.0,350.0,340.000000,0.600000,125700.0,1396.0,47.412930,-121.441530,119000.0
21217,WA,Graham,Whitman Lake Drive E,98338.0,0.0,0.0,324.0,861.111111,0.204300,277800.0,1200.0,46.964764,-122.258110,279000.0
21283,WA,Concrete,South Shore Drive,98237.0,0.0,1.0,540.0,275.925926,0.400000,136800.0,1529.0,48.532800,-121.837395,149000.0
21664,WV,Charles Town,Jefferson Ave,25414.0,0.0,0.0,860.0,139.534884,0.170000,121000.0,1394.0,39.288340,-77.848560,120000.0
22069,WI,Alvin,River Bank Ln,54542.0,0.0,0.0,320.0,234.375000,0.489991,NaN,NaN,46.029110,-88.837680,75000.0
22300,WY,Pinedale,Sylvan Ln,82941.0,0.0,0.0,320.0,467.187500,NaN,NaN,394.0,42.951412,-109.777370,149500.0

In [88]:
# We considered zero values in bedroom,
# bathroom and area as missing values because
# houses cannot realistically have zero rooms
zero_as_missing = [ 'bathroom', 'area']
for col in zero_as_missing:
    df[col] = df[col].replace(0, np.nan)

df['bathroom'] = df['bathroom'].round(1)

for c in ['state', 'city']:
    df[c] = df[c].astype(str).str.strip().str.title()

## ppsq = listedprice/area  (data leakage)
## marketestimate (data leakage)
df.drop(columns=['marketestimate', 'street', 'zipcode'], inplace=True)
df = df.dropna(subset=['listedprice']).reset_index(drop=True)

In [89]:
low, high = df['listedprice'].quantile([0.005, 0.995])

outliers = df[(df['listedprice'] < low) | (df['listedprice'] > high)]

print("Number of outliers:", outliers.shape[0])

outliers.sort_values("listedprice")[[
    "listedprice",
    "area",
    "bedroom",
    "bathroom",
    "lotarea",
    "city",
    "state",
    "latitude",
    "ppsq",
    "longitude"
]].head(20)

Number of outliers: 228

,listedprice,area,bedroom,bathroom,lotarea,city,state,latitude,ppsq,longitude
15625,4888.0,2538.0,4.0,2.0,0.114800,Toledo,Oh,41.658035,1.925926,-83.566570
16904,4900.0,782.0,2.0,1.0,0.050000,Turtle Creek,Pa,40.412724,6.265985,-79.827255
14347,6000.0,1728.0,4.0,2.0,NaN,Syracuse,Ny,43.014565,3.472222,-76.142624
6665,7500.0,3000.0,2.0,1.0,0.054522,Ackley,Ia,42.554363,2.500000,-93.053400
6992,8000.0,1000.0,2.0,1.0,NaN,Wichita,Ks,37.652090,8.000000,-97.398400
18665,10000.0,2080.0,3.0,3.0,4.880000,Sparta,Tn,35.921963,4.807692,-85.493490
12150,10000.0,1972.0,4.0,2.0,NaN,Glenvil,Ne,40.503395,5.070994,-98.255530
21460,12500.0,1100.0,2.0,1.0,0.280000,Princeton,Wv,37.383610,11.363636,-81.094930
21458,12500.0,1610.0,4.0,2.0,1.460000,Harts,Wv,38.000200,7.763975,-82.098274
15995,12900.0,1194.0,2.0,1.0,0.161000,Ponca City,Ok,36.709100,10.804020,-97.082140
14376,13000.0,2016.0,4.0,2.0,NaN,Syracuse,Ny,43.025500,6.448413,-76.143570
13280,14500.0,396.0,1.0,1.0,NaN,Lancaster,Nh,44.466460,36.616162,-71.548570
16637,14900.0,520.0,2.0,1.0,NaN,Portland,Or,45.497540,28.653846,-122.549910
6814,14900.0,1884.0,5.0,2.0,0.210000,Fort Scott,Ks,37.828120,7.908705,-94.707670
10120,15000.0,1713.0,4.0,2.0,0.000000,Luverne,Mn,43.660748,8.756567,-96.244800
18599,15000.0,624.0,3.0,1.0,NaN,Pierre,Sd,44.380253,24.038462,-100.347360
21729,15000.0,1384.0,4.0,1.0,0.100000,Bluefield,Wv,37.318966,10.838150,-81.264540
15611,16000.0,3000.0,5.0,2.0,0.500000,Steubenville,Oh,40.358940,5.333333,-80.625060
6020,16500.0,1266.0,4.0,1.0,0.109000,Gary,In,41.577710,13.033175,-87.331406
15108,19900.0,1128.0,2.0,1.0,0.160000,Kenmare,Nd,48.676080,17.641844,-102.082070

In [90]:
outliers.sort_values(
    "listedprice",
    ascending=False
)[[
    "listedprice",
    "area",
    "bedroom",
    "bathroom",
    "lotarea",
    "city",
    "ppsq",
    "state"
]].head(20)

,listedprice,area,bedroom,bathroom,lotarea,city,ppsq,state
12482,76000000.0,14197.0,7.0,NaN,4.972000,Incline Village,5353.243643,Nv
11568,72000000.0,45000.0,2.0,2.0,348.000000,Dayton,1600.000000,Mt
19451,65000000.0,22000.0,8.0,12.0,8.978000,Houston,2954.545455,Tx
18777,65000000.0,10626.0,5.0,9.0,383.620000,Franklin,6117.071334,Tn
12553,49500000.0,16232.0,8.0,NaN,5.140000,Crystal Bay,3049.531789,Nv
18755,40000000.0,19811.0,5.0,10.0,49.720000,Nashville,2019.080309,Tn
22462,37500000.0,9696.0,4.0,7.0,4.530000,Wilson,3867.574257,Wy
8679,34900000.0,30000.0,5.0,10.0,9.650000,Potomac,1163.333333,Md
22312,32750000.0,7984.0,5.0,7.0,37.060000,Jackson,4101.953908,Wy
9502,31000000.0,10858.0,5.0,8.0,0.099862,Boston,2855.037760,Ma
8632,30000000.0,13458.0,6.0,5.0,490.170000,Leonardtown,2229.157379,Md
21904,30000000.0,20000.0,10.0,12.0,12.000000,Lake Geneva,1500.000000,Wi
2355,28888000.0,14000.0,7.0,9.0,1.308200,Los Angeles,2063.428571,Ca
11509,28500000.0,15264.0,6.0,11.0,5.850000,Lakeside,1867.138365,Mt
9523,28000000.0,23374.0,9.0,11.0,3.101200,Brookline,1197.912210,Ma
22383,27000000.0,8237.0,7.0,9.0,4.640000,Jackson,3277.892437,Wy
9307,26500000.0,8350.0,7.0,9.0,3.330000,West Tisbury,3173.652695,Ma
20089,26200000.0,9580.0,11.0,8.0,345.000000,Ferrisburgh,2734.864301,Vt
12834,25000000.0,10176.0,5.0,9.0,1.380000,Rye,2456.761006,Nh
14027,25000000.0,13500.0,8.0,12.0,2.210000,Santa Fe,1851.851852,Nm

In [91]:
df.sort_values("ppsq").head(20)

,state,city,bedroom,bathroom,area,ppsq,lotarea,rentestimate,latitude,longitude,listedprice
15625,Oh,Toledo,4.0,2.0,2538.0,1.925926,0.114800,964.0,41.658035,-83.566570,4888.0
6665,Ia,Ackley,2.0,1.0,3000.0,2.500000,0.054522,NaN,42.554363,-93.053400,7500.0
14347,Ny,Syracuse,4.0,2.0,1728.0,3.472222,NaN,2250.0,43.014565,-76.142624,6000.0
18665,Tn,Sparta,3.0,3.0,2080.0,4.807692,4.880000,1999.0,35.921963,-85.493490,10000.0
12150,Ne,Glenvil,4.0,2.0,1972.0,5.070994,NaN,1300.0,40.503395,-98.255530,10000.0
15611,Oh,Steubenville,5.0,2.0,3000.0,5.333333,0.500000,NaN,40.358940,-80.625060,16000.0
14928,Nd,Hunter,7.0,11.0,25496.0,5.883276,1.580000,2674.0,47.191130,-97.213760,150000.0
16904,Pa,Turtle Creek,2.0,1.0,782.0,6.265985,0.050000,963.0,40.412724,-79.827255,4900.0
14376,Ny,Syracuse,4.0,2.0,2016.0,6.448413,NaN,2258.0,43.025500,-76.143570,13000.0
6109,In,Gary,6.0,3.0,3225.0,6.821705,0.086000,1994.0,41.601406,-87.334950,22000.0
5850,In,Gary,9.0,3.0,3369.0,7.420600,0.083300,NaN,41.588600,-87.345380,25000.0
21458,Wv,Harts,4.0,2.0,1610.0,7.763975,1.460000,749.0,38.000200,-82.098274,12500.0
12865,Nh,Berlin,12.0,4.0,5120.0,7.792969,0.050000,9999.0,44.476196,-71.171300,39900.0
6814,Ks,Fort Scott,5.0,2.0,1884.0,7.908705,0.210000,1494.0,37.828120,-94.707670,14900.0
6992,Ks,Wichita,2.0,1.0,1000.0,8.000000,NaN,900.0,37.652090,-97.398400,8000.0
12313,Ne,Ravenna,2.0,1.0,12075.0,8.190476,0.241047,1494.0,41.031460,-98.913760,98900.0
10120,Mn,Luverne,4.0,2.0,1713.0,8.756567,0.000000,NaN,43.660748,-96.244800,15000.0
7853,La,Arcadia,4.0,2.0,2707.0,9.235316,0.379000,1700.0,32.549274,-92.917120,25000.0
14246,Ny,Rochester,6.0,2.0,2658.0,9.367946,0.101000,NaN,43.180504,-77.616860,24900.0
8992,Md,Cumberland,4.0,2.0,2196.0,10.245902,0.071740,NaN,39.633710,-78.759010,22500.0

In [92]:
df.sort_values("ppsq", ascending=False).head(20)

,state,city,bedroom,bathroom,area,ppsq,lotarea,rentestimate,latitude,longitude,listedprice
18777,Tn,Franklin,5.0,9.0,10626.0,6117.071334,383.620000,32029.0,35.927906,-87.083510,65000000.0
2365,Ca,Aptos,3.0,2.0,1859.0,5379.236148,0.183999,9602.0,36.957348,-121.888050,10000000.0
12482,Nv,Incline Village,7.0,NaN,14197.0,5353.243643,4.972000,212834.0,39.235850,-119.940020,76000000.0
2026,Ca,Encinitas,4.0,3.0,1757.0,4439.385316,0.107323,15532.0,33.046840,-117.297240,7800000.0
11699,Mt,Virginia City,4.0,3.0,2280.0,4166.666667,379.250000,29736.0,45.245230,-111.887850,9500000.0
22312,Wy,Jackson,5.0,7.0,7984.0,4101.953908,37.060000,92603.0,43.589115,-110.776680,32750000.0
22462,Wy,Wilson,4.0,7.0,9696.0,3867.574257,4.530000,124969.0,43.578857,-110.803955,37500000.0
17508,Ri,Westerly,6.0,6.0,4976.0,3616.358521,0.980005,NaN,41.314175,-71.841860,17995000.0
1698,Ar,Huntington,3.0,2.0,1400.0,3428.571429,70.010000,NaN,35.136562,-94.289154,4800000.0
22383,Wy,Jackson,7.0,9.0,8237.0,3277.892437,4.640000,NaN,43.500060,-110.769295,27000000.0
13259,Nh,Meredith,4.0,1.0,1309.0,3208.556150,0.550000,NaN,43.674960,-71.435120,4200000.0
9307,Ma,West Tisbury,7.0,9.0,8350.0,3173.652695,3.330000,15680.0,41.448246,-70.667440,26500000.0
20278,Vt,Ludlow,5.0,2.0,3150.0,3173.204762,127.000000,3790.0,43.387386,-72.713400,9995595.0
19635,Ut,Park City,4.0,8.0,8000.0,3112.500000,5.610000,92781.0,40.757633,-111.435600,24900000.0
12553,Nv,Crystal Bay,8.0,NaN,16232.0,3049.531789,5.140000,NaN,39.235703,-120.001180,49500000.0
19451,Tx,Houston,8.0,12.0,22000.0,2954.545455,8.978000,73059.0,29.764520,-95.492050,65000000.0
20126,Vt,Morrisville,4.0,6.0,6878.0,2907.822041,196.950000,11629.0,44.542725,-72.669670,20000000.0
13656,Nj,Avalon,5.0,6.0,4529.0,2869.286818,0.151515,NaN,39.101650,-74.710464,12995000.0
9502,Ma,Boston,5.0,8.0,10858.0,2855.037760,0.099862,113746.0,42.356625,-71.068320,31000000.0
20089,Vt,Ferrisburgh,11.0,8.0,9580.0,2734.864301,345.000000,25774.0,44.237360,-73.315285,26200000.0

In [93]:
# remove unrealistic low values only
df = df[df["ppsq"] >= 5]

# remove clearly invalid cheap houses
df = df[df["listedprice"] >= 20000]

df = df.drop(columns=["ppsq"])

In [94]:
from datasist.structdata import detect_outliers
numeric_lst = df.select_dtypes(include = 'number').columns
for col in numeric_lst :
    outliers = detect_outliers(data = df , n = 0 , features = [col])
    print(col)
    print(outliers)
    print(len(outliers)/df[col].shape[0]*100)
    print('-'*50)

bedroom
[]
0.0
--------------------------------------------------
bathroom
[]
0.0
--------------------------------------------------
area
[27, 139, 145, 169, 278, 347, 444, 451, 513, 519, 556, 578, 582, 621, 649, 651, 680, 719, 743, 745, 747, 771, 800, 816, 835, 840, 855, 861, 905, 906, 924, 928, 968, 973, 1005, 1032, 1076, 1109, 1117, 1158, 1225, 1234, 1264, 1280, 1281, 1308, 1311, 1336, 1358, 1403, 1449, 1497, 1504, 1534, 1657, 1694, 1768, 1775, 1788, 1837, 1840, 1874, 1877, 1933, 1972, 1995, 2054, 2056, 2120, 2199, 2208, 2217, 2245, 2268, 2279, 2289, 2302, 2308, 2310, 2314, 2315, 2320, 2328, 2343, 2354, 2355, 2366, 2378, 2405, 2412, 2426, 2433, 2451, 2453, 2455, 2460, 2472, 2474, 2476, 2484, 2496, 2501, 2503, 2506, 2511, 2526, 2535, 2541, 2545, 2546, 2560, 2564, 2569, 2575, 2598, 2602, 2605, 2606, 2618, 2630, 2636, 2638, 2645, 2646, 2652, 2656, 2678, 2688, 2705, 2715, 2720, 2723, 2729, 2731, 2740, 2741, 2743, 2744, 2746, 2753, 2754, 2763, 2775, 2783, 2785, 2795, 2803, 2805, 2808, 2809, 2815, 2817, 2832, 2857, 2860, 2861, 2886, 2890, 2898, 2913, 2920, 2925, 2990, 2994, 2998, 3014, 3037, 3066, 3084, 3113, 3123, 3163, 3167, 3182, 3192, 3206, 3207, 3248, 3262, 3263, 3272, 3274, 3277, 3278, 3319, 3364, 3393, 3398, 3408, 3419, 3425, 3482, 3497, 3509, 3550, 3552, 3560, 3589, 3677, 3701, 3704, 3709, 3754, 3758, 3768, 3773, 3836, 3877, 3881, 3924, 3930, 3936, 3975, 4112, 4124, 4162, 4225, 4325, 4353, 4366, 4368, 4375, 4376, 4382, 4389, 4390, 4391, 4393, 4399, 4400, 4401, 4421, 4431, 4444, 4447, 4448, 4459, 4460, 4462, 4468, 4498, 4499, 4545, 4546, 4554, 4580, 4592, 4597, 4599, 4600, 4635, 4648, 4655, 4670, 4671, 4679, 4686, 4719, 4734, 4740, 4753, 4757, 4758, 4799, 4835, 4893, 4936, 4950, 4971, 4972, 4984, 4992, 5028, 5035, 5047, 5048, 5077, 5104, 5105, 5109, 5127, 5145, 5163, 5215, 5221, 5271, 5283, 5343, 5416, 5459, 5497, 5624, 5637, 5645, 5668, 5673, 5683, 5711, 5724, 5753, 5793, 5794, 5807, 5819, 5902, 5916, 5953, 5989, 6021, 6052, 6088, 6122, 6167, 6187, 6191, 6237, 6251, 6265, 6346, 6468, 6520, 6531, 6595, 6603, 6604, 6647, 6687, 6694, 6712, 6716, 6721, 6744, 6745, 6754, 6779, 6796, 6810, 6879, 6899, 6902, 6911, 6934, 6966, 6967, 6981, 6984, 6989, 6999, 7003, 7034, 7042, 7067, 7090, 7093, 7102, 7126, 7145, 7176, 7179, 7181, 7182, 7189, 7203, 7209, 7232, 7245, 7311, 7389, 7404, 7414, 7565, 7595, 7606, 7622, 7639, 7647, 7736, 7769, 7770, 7783, 7815, 7825, 7827, 7830, 7899, 7925, 7936, 7942, 7953, 7955, 7969, 7974, 7983, 7987, 7989, 8015, 8020, 8025, 8036, 8040, 8042, 8094, 8127, 8128, 8168, 8188, 8207, 8216, 8248, 8253, 8257, 8276, 8316, 8337, 8341, 8349, 8385, 8397, 8404, 8419, 8451, 8460, 8480, 8487, 8531, 8533, 8546, 8547, 8557, 8592, 8623, 8629, 8631, 8632, 8634, 8655, 8658, 8674, 8677, 8679, 8680, 8686, 8729, 8735, 8736, 8759, 8765, 8776, 8787, 8798, 8808, 8816, 8850, 8859, 8899, 8929, 8952, 8978, 8981, 9006, 9034, 9037, 9055, 9075, 9111, 9247, 9249, 9307, 9321, 9359, 9369, 9413, 9422, 9465, 9472, 9495, 9502, 9523, 9524, 9530, 9545, 9549, 9566, 9569, 9574, 9601, 9615, 9629, 9663, 9672, 9674, 9681, 9697, 9714, 9717, 9746, 9816, 9820, 9832, 9842, 9885, 9918, 9963, 9973, 9984, 10058, 10090, 10109, 10125, 10195, 10235, 10268, 10337, 10368, 10399, 10413, 10419, 10423, 10457, 10465, 10475, 10478, 10491, 10608, 10643, 10689, 10698, 10865, 10886, 10904, 10958, 10976, 11000, 11004, 11005, 11055, 11080, 11133, 11144, 11150, 11185, 11207, 11214, 11304, 11305, 11361, 11369, 11373, 11381, 11384, 11477, 11499, 11509, 11513, 11523, 11534, 11550, 11558, 11559, 11568, 11569, 11570, 11585, 11587, 11590, 11616, 11621, 11624, 11625, 11626, 11634, 11640, 11661, 11669, 11685, 11697, 11704, 11706, 11723, 11726, 11732, 11733, 11744, 11747, 11758, 11770, 11773, 11777, 11798, 11807, 11811, 11823, 11838, 11845, 11854, 11855, 11861, 11876, 11885, 11890, 11894, 11896, 11898, 11971, 11979, 11981, 11995, 12009, 12023, 12027, 12050, 12052, 12070, 12114, 12115, 12131, 12136, 12139, 12152, 12169, 12171, 12176, 12191, 12209, 12228, 12240, 12246, 12277, 12280, 12293, 12303, 12307, 12313, 12332, 12334, 12342, 12346, 12350, 12354, 12365, 12367, 12369, 12371, 12385, 12395, 12425, 12439, 12440, 12476, 12482, 12489, 12542, 12553, 12555, 12565, 12600, 12604, 12606, 12617, 12625, 12642, 12647, 12653, 12655, 12717, 12727, 12739, 12741, 12763, 12770, 12772, 12773, 12782, 12783, 12788, 12793, 12815, 12834, 12839, 12841, 12856, 12865, 12935, 12948, 12954, 12968, 13053, 13055, 13077, 13080, 13090, 13125, 13129, 13138, 13190, 13201, 13205, 13246, 13275, 13283, 13310, 13325, 13339, 13365, 13373, 13377, 13386, 13424, 13430, 13436, 13457, 13514, 13525, 13535, 13538, 13569, 13648, 13656, 13692, 13807, 13837, 13844, 13859, 13903, 13913, 13934, 13937, 14027, 14035, 14049, 14068, 14118, 14231, 14426, 14444, 14477, 14545, 14559, 14734, 14761, 14786, 14866, 14928, 14950, 14957, 14995, 15011, 15028, 15060, 15071, 15092, 15103, 15104, 15117, 15129, 15136, 15140, 15142, 15143, 15146, 15177, 15182, 15195, 15211, 15223, 15225, 15226, 15231, 15236, 15240, 15241, 15250, 15259, 15264, 15285, 15289, 15298, 15299, 15309, 15312, 15315, 15317, 15339, 15359, 15364, 15369, 15395, 15431, 15576, 15646, 15731, 15801, 15803, 15855, 15886, 15902, 16031, 16112, 16142, 16144, 16150, 16180, 16183, 16192, 16210, 16212, 16239, 16247, 16256, 16273, 16289, 16296, 16306, 16326, 16328, 16365, 16420, 16472, 16480, 16506, 16561, 16577, 16630, 16685, 16946, 17010, 17079, 17142, 17383, 17388, 17399, 17441, 17447, 17453, 17473, 17479, 17508, 17542, 17562, 17565, 17567, 17572, 17578, 17579, 17624, 17639, 17642, 17647, 17665, 17672, 17694, 17695, 17712, 17718, 17908, 17939, 17975, 18040, 18073, 18082, 18094, 18103, 18129, 18149, 18155, 18178, 18179, 18218, 18240, 18256, 18278, 18287, 18297, 18322, 18329, 18339, 18348, 18364, 18371, 18373, 18401, 18408, 18412, 18417, 18436, 18442, 18457, 18462, 18463, 18492, 18529, 18536, 18549, 18560, 18573, 18583, 18587, 18610, 18614, 18617, 18670, 18755, 18777, 18816, 18836, 18837, 18877, 18899, 18983, 18995, 19035, 19036, 19044, 19048, 19065, 19073, 19129, 19143, 19219, 19302, 19303, 19330, 19346, 19372, 19378, 19396, 19418, 19448, 19451, 19454, 19466, 19506, 19529, 19549, 19550, 19561, 19577, 19591, 19594, 19598, 19610, 19618, 19620, 19634, 19635, 19657, 19677, 19685, 19712, 19723, 19724, 19743, 19758, 19778, 19787, 19790, 19798, 19799, 19819, 19839, 19851, 19857, 19864, 19878, 19893, 19894, 19899, 19902, 19904, 19910, 19924, 19932, 19950, 19965, 19993, 20015, 20061, 20071, 20073, 20079, 20085, 20089, 20111, 20126, 20136, 20137, 20163, 20169, 20176, 20195, 20198, 20204, 20206, 20209, 20229, 20230, 20235, 20256, 20259, 20271, 20284, 20288, 20299, 20304, 20312, 20320, 20325, 20346, 20347, 20364, 20370, 20371, 20376, 20385, 20393, 20415, 20418, 20419, 20445, 20612, 20646, 20731, 20732, 20818, 20836, 20898, 21111, 21121, 21184, 21187, 21205, 21237, 21351, 21361, 21408, 21498, 21546, 21581, 21592, 21607, 21611, 21653, 21661, 21687, 21718, 21753, 21771, 21826, 21869, 21872, 21904, 21910, 21952, 21965, 21997, 21999, 22005, 22006, 22075, 22186, 22211, 22234, 22278, 22294, 22299, 22312, 22339, 22365, 22375, 22383, 22390, 22397, 22408, 22424, 22426, 22438, 22457, 22458, 22459, 22462, 22475, 22513, 22521, 22525, 22526, 22532, 22545, 22572, 22573, 22579, 22584, 22595, 22601, 22603, 22637, 22640, 22659, 22662, 22667]
4.850383970341602
--------------------------------------------------
lotarea
[]
0.0
--------------------------------------------------
rentestimate
[]
0.0
--------------------------------------------------
latitude
[475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961]
2.14935122252626
--------------------------------------------------
longitude
[475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 536, 537, 538, 540, 541, 542, 543, 544, 545, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 559, 560, 561, 562, 563, 564, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 595, 596, 597, 598, 599, 600, 601, 602, 604, 605, 607, 608, 609, 610, 611, 612, 613, 614, 615, 617, 619, 620, 621, 622, 623, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 646, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 663, 664, 665, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 691, 692, 693, 694, 696, 697, 698, 699, 700, 702, 703, 704, 705, 706, 707, 708, 709, 711, 713, 714, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 782, 783, 784, 786, 787, 788, 789, 790, 791, 793, 794, 795, 796, 797, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 878, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 927, 928, 929, 930, 931, 932, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961]
1.9639862300291289
--------------------------------------------------
listedprice

### Feature Engineering

In [117]:
df['area'] = df['area'].replace(0, np.nan)
df['lotarea'] = df['lotarea'].replace(0, np.nan)
df['lot_to_area_ratio'] = df['lotarea'] / df['area']

In [118]:
df.shape

(22658, 11)

In [119]:
((df.isnull().sum()/len(df))*100).sort_values(ascending=False)

rentestimate         26.343896
lotarea               4.916586
lot_to_area_ratio     4.916586
bathroom              0.485480
bedroom               0.061788
city                  0.000000
state                 0.000000
area                  0.000000
latitude              0.000000
longitude             0.000000
listedprice           0.000000
dtype: float64

### Analysis

## Preprocessing Pipelines

In [120]:
num_cols = ['bedroom','bathroom','area','lotarea','rentestimate',
            'latitude','longitude','lot_to_area_ratio',]
ohe_cat  = ['state']
be_cat = ['city']

In [121]:
x = df.drop('listedprice', axis=1)
y = df['listedprice']

## PipeLine

### Numerical Pipeline

In [122]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler

simple_imputer = SimpleImputer(strategy='median')
rc = RobustScaler()

num_pipe = Pipeline([('SimpleImputer', simple_imputer), ('Scaling', rc)])

## Categorical Pipelines

In [123]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import  OneHotEncoder


ohe_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ohe', OneHotEncoder(drop='first', handle_unknown='ignore'))
])
ohe_pipe

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('ohe', OneHotEncoder(drop='first', handle_unknown='ignore'))])

In [124]:
from category_encoders import BinaryEncoder

be = BinaryEncoder()

be_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('BE', be)
])
be_pipe

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('BE', BinaryEncoder())])

In [125]:
from sklearn.compose import ColumnTransformer 

preprocessing= ColumnTransformer([
    ('num', num_pipe, num_cols),
    ('ohe', ohe_pipe, ohe_cat),
    ('binary', be_pipe, be_cat)
])
display(preprocessing)

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('SimpleImputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('Scaling', RobustScaler())]),
                                 ['bedroom', 'bathroom', 'area', 'lotarea',
                                  'rentestimate', 'latitude', 'longitude',
                                  'lot_to_area_ratio']),
                                ('ohe',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('ohe',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'))]),
                                 ['state']),
                                ('binary',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('BE', BinaryEncoder())]),
                                 ['city'])])

In [126]:
'''from sklearn.model_selection import train_test_split

x = df.drop(columns=['listedprice'])
y = df['listedprice']

x_train,x_test,y_train,y_test = train_test_split(
    x,y, test_size=0.2, random_state=42
)
print('Train:', x_train.shape, ' Test:',x_test.shape) '''

"from sklearn.model_selection import train_test_split\n\nx = df.drop(columns=['listedprice'])\ny = df['listedprice']\n\nx_train,x_test,y_train,y_test = train_test_split(\n    x,y, test_size=0.2, random_state=42\n)\nprint('Train:', x_train.shape, ' Test:',x_test.shape) "

In [127]:
print(df.columns.tolist())

['state', 'city', 'bedroom', 'bathroom', 'area', 'lotarea', 'rentestimate', 'latitude', 'longitude', 'listedprice', 'lot_to_area_ratio']

### Algorithm Selection

In [128]:
((df.isnull().sum()/len(df))*100).sort_values(ascending=False)

rentestimate         26.343896
lotarea               4.916586
lot_to_area_ratio     4.916586
bathroom              0.485480
bedroom               0.061788
city                  0.000000
state                 0.000000
area                  0.000000
latitude              0.000000
longitude             0.000000
listedprice           0.000000
dtype: float64

In [129]:
from sklearn.pipeline import Pipeline  
from sklearn.model_selection import cross_validate, KFold
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.compose import TransformedTargetRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import cross_validate


cv = KFold(n_splits=5, shuffle=True, random_state=42)
models = [
    ('Linear Regression', LinearRegression()),
    ('Ridge', Ridge(random_state=42)),
    ('Lasso', Lasso(random_state=42)),
    ('KNN', KNeighborsRegressor()),
    ('Decision Tree', DecisionTreeRegressor(random_state=42)),
    ('Random Forest', RandomForestRegressor(random_state=42, n_jobs=-1)),
    ('Gradient Boosting', GradientBoostingRegressor(random_state=42)),
    ('XGBoost', XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)),]

for name, model in models:

    pipeline = Pipeline([
        ('preprocessing', preprocessing),
        ('model', model)
    ])

    model_final = TransformedTargetRegressor(
        regressor=pipeline,
        func=np.log1p,
        inverse_func=np.expm1
    )

    result = cross_validate(
        model_final,x,y,cv=cv,scoring='r2',return_train_score=True,n_jobs=-1
    )

    print(name)
    print('train score:', result['train_score'].mean())
    print('val score:', result['test_score'].mean())
    print('-' * 40)

Linear Regression
train score: -1491813.8728101705
val score: -571150181.0167472
----------------------------------------
Ridge
train score: -1487365.800525675
val score: -568491556.57285
----------------------------------------
Lasso
train score: -0.26246822394283065
val score: -0.8697517616787493
----------------------------------------
KNN
train score: 0.6461553634519109
val score: 0.5794466007807049
----------------------------------------
Decision Tree
train score: 1.0
val score: 0.18077911859192317
----------------------------------------
Random Forest
train score: 0.7949367616651063
val score: 0.5093688257781517
----------------------------------------
Gradient Boosting
train score: 0.6286475467601369
val score: 0.47104551610474343
----------------------------------------
XGBoost
train score: 0.8648788545746917
val score: 0.5247891447491386
----------------------------------------

In [130]:
# loggg
# 1) Random Forest         0.620
# 2) Gradient Boosting     0.615
# 3) XGBoost               0.601
# KNN                      0.507

In [131]:
'''from sklearn.neighbors import KNeighborsRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import TransformedTargetRegressor
from sklearn.model_selection import RandomizedSearchCV


xgb_pipeline = Pipeline([
    ('preprocessing', preprocessing),
    ('model', XGBRegressor(random_state=42, n_jobs=-1, verbosity=0)),
])
 
xgb_model = TransformedTargetRegressor(
    regressor=xgb_pipeline,
    func=np.log1p,
    inverse_func=np.expm1,
)

param_grid = {
    'regressor__model__max_depth':        [4, 5, 6],
    'regressor__model__learning_rate':    [0.03, 0.05, 0.1],
    'regressor__model__n_estimators':     [300, 500, 700],
    'regressor__model__subsample':        [0.7, 0.8, 0.9],
    'regressor__model__colsample_bytree': [0.7, 0.8, 0.9],
    'regressor__model__min_child_weight': [1, 3, 5],
    'regressor__model__reg_lambda':       [1, 5, 10],
}
 
cv = KFold(n_splits=5, shuffle=True, random_state=42)
 
search = RandomizedSearchCV(
    estimator=xgb_model,
    param_distributions=param_grid,
    n_iter=40,
    cv=cv,
    scoring='r2',
    random_state=42,
    n_jobs=-1,
    verbose=1,
)
 
 
search.fit(x_train, y_train)

print("Best CV score:", search.best_score_)
print("Best params:", search.best_params_)'''

'from sklearn.neighbors import KNeighborsRegressor\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.compose import TransformedTargetRegressor\nfrom sklearn.model_selection import RandomizedSearchCV\n\n\nxgb_pipeline = Pipeline([\n    (\'preprocessing\', preprocessing),\n    (\'model\', XGBRegressor(random_state=42, n_jobs=-1, verbosity=0)),\n])\n\nxgb_model = TransformedTargetRegressor(\n    regressor=xgb_pipeline,\n    func=np.log1p,\n    inverse_func=np.expm1,\n)\n\nparam_grid = {\n    \'regressor__model__max_depth\':        [4, 5, 6],\n    \'regressor__model__learning_rate\':    [0.03, 0.05, 0.1],\n    \'regressor__model__n_estimators\':     [300, 500, 700],\n    \'regressor__model__subsample\':        [0.7, 0.8, 0.9],\n    \'regressor__model__colsample_bytree\': [0.7, 0.8, 0.9],\n    \'regressor__model__min_child_weight\': [1, 3, 5],\n    \'regressor__model__reg_lambda\':       [1, 5, 10],\n}\n\ncv = KFold(n_splits=5, shuffle=True, random_state=42)\n\nsearch = RandomizedSearchCV(\n    estimator=xgb_model,\n    param_distributions=param_grid,\n    n_iter=40,\n    cv=cv,\n    scoring=\'r2\',\n    random_state=42,\n    n_jobs=-1,\n    verbose=1,\n)\n\n\nsearch.fit(x_train, y_train)\n\nprint("Best CV score:", search.best_score_)\nprint("Best params:", search.best_params_)'

In [132]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import TransformedTargetRegressor
from sklearn.model_selection import RandomizedSearchCV


rf_pipeline = Pipeline(steps=[
    ('preprocessing', preprocessing),
    ('model', RandomForestRegressor(random_state=42, n_jobs=-1))
])

model = TransformedTargetRegressor(
    regressor=rf_pipeline,
    func=np.log1p,
    inverse_func=np.expm1
)

param_dist = {
    'regressor__model__n_estimators': [200, 400, 600, 800, 1000],
    'regressor__model__max_depth': [None, 5, 10, 15, 20, 30],
    'regressor__model__min_samples_split': [2, 5, 10, 20],
    'regressor__model__min_samples_leaf': [1, 2, 4, 8],
    'regressor__model__max_features': ['sqrt', 'log2', 0.5, 0.8],
    'regressor__model__bootstrap': [True, False]
}


search = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_dist,
    n_iter=40,
    cv=5,
    scoring='r2',
    verbose=2,
    random_state=42,
    n_jobs=-1,
    return_train_score=True
)

search.fit(x, y)


print("Best R2:", search.best_score_)
print("Best Params:", search.best_params_)

Fitting 5 folds for each of 40 candidates, totalling 200 fits
Best R2: 0.5002049599543961
Best Params: {'regressor__model__n_estimators': 400, 'regressor__model__min_samples_split': 2, 'regressor__model__min_samples_leaf': 1, 'regressor__model__max_features': 0.8, 'regressor__model__max_depth': 10, 'regressor__model__bootstrap': True}

In [133]:
'''
import numpy as np
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import TransformedTargetRegressor
from sklearn.model_selection import RandomizedSearchCV

xgb_pipeline = Pipeline(steps=[
    ('preprocessing', preprocessing),
    ('model', XGBRegressor(
        objective='reg:squarederror',
        random_state=42,
        n_jobs=-1
    ))
])

model = TransformedTargetRegressor(
    regressor=xgb_pipeline,
    func=np.log1p,
    inverse_func=np.expm1
)

param_dist = {
    'regressor__model__n_estimators': [200, 400, 600, 800, 1000],
    'regressor__model__max_depth': [3, 5, 7, 9],
    'regressor__model__learning_rate': [0.01, 0.03, 0.05, 0.1],
    'regressor__model__subsample': [0.6, 0.8, 1.0],
    'regressor__model__colsample_bytree': [0.6, 0.8, 1.0],
    'regressor__model__min_child_weight': [1, 3, 5, 7],
    'regressor__model__gamma': [0, 0.1, 0.3, 0.5]
}

search = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_dist,
    n_iter=40,        
    cv=5,
    scoring='r2',
    verbose=2,
    random_state=42,
    n_jobs=-1,
    return_train_score=True
)

search.fit(x, y)

print("Best R2:", search.best_score_)
print("Best Params:", search.best_params_)

Best R2: 0.4767723997157445
Best Params: {'regressor__model__subsample': 0.6, 'regressor__model__n_estimators': 400, 'regressor__model__min_child_weight': 5, 'regressor__model__max_depth': 3, 'regressor__model__learning_rate': 0.05, 'regressor__model__gamma': 0.3, 'regressor__model__colsample_bytree': 0.6}'''

'\nimport numpy as np\nfrom xgboost import XGBRegressor\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.compose import TransformedTargetRegressor\nfrom sklearn.model_selection import RandomizedSearchCV\n\nxgb_pipeline = Pipeline(steps=[\n    (\'preprocessing\', preprocessing),\n    (\'model\', XGBRegressor(\n        objective=\'reg:squarederror\',\n        random_state=42,\n        n_jobs=-1\n    ))\n])\n\nmodel = TransformedTargetRegressor(\n    regressor=xgb_pipeline,\n    func=np.log1p,\n    inverse_func=np.expm1\n)\n\nparam_dist = {\n    \'regressor__model__n_estimators\': [200, 400, 600, 800, 1000],\n    \'regressor__model__max_depth\': [3, 5, 7, 9],\n    \'regressor__model__learning_rate\': [0.01, 0.03, 0.05, 0.1],\n    \'regressor__model__subsample\': [0.6, 0.8, 1.0],\n    \'regressor__model__colsample_bytree\': [0.6, 0.8, 1.0],\n    \'regressor__model__min_child_weight\': [1, 3, 5, 7],\n    \'regressor__model__gamma\': [0, 0.1, 0.3, 0.5]\n}\n\nsearch = RandomizedSearchCV(\n    estimator=model,\n    param_distributions=param_dist,\n    n_iter=40,        \n    cv=5,\n    scoring=\'r2\',\n    verbose=2,\n    random_state=42,\n    n_jobs=-1,\n    return_train_score=True\n)\n\nsearch.fit(x, y)\n\nprint("Best R2:", search.best_score_)\nprint("Best Params:", search.best_params_)\n\nBest R2: 0.4767723997157445\nBest Params: {\'regressor__model__subsample\': 0.6, \'regressor__model__n_estimators\': 400, \'regressor__model__min_child_weight\': 5, \'regressor__model__max_depth\': 3, \'regressor__model__learning_rate\': 0.05, \'regressor__model__gamma\': 0.3, \'regressor__model__colsample_bytree\': 0.6}'

In [134]:
final_model = search.best_estimator_
final_model.fit(x,y)
final_model

TransformedTargetRegressor(func=<ufunc 'log1p'>, inverse_func=<ufunc 'expm1'>,
                           regressor=Pipeline(steps=[('preprocessing',
                                                      ColumnTransformer(transformers=[('num',
                                                                                       Pipeline(steps=[('SimpleImputer',
                                                                                                        SimpleImputer(strategy='median')),
                                                                                                       ('Scaling',
                                                                                                        RobustScaler())]),
                                                                                       ['bedroom',
                                                                                        'bathroom',
                                                                                        'area',
                                                                                        'lotarea',
                                                                                        'rentestimate',
                                                                                        'latitude',
                                                                                        'longitude',
                                                                                        'lot_to_area_ratio']...
                                                                                       Pipeline(steps=[('imputer',
                                                                                                        SimpleImputer(strategy='most_frequent')),
                                                                                                       ('ohe',
                                                                                                        OneHotEncoder(drop='first',
                                                                                                                      handle_unknown='ignore'))]),
                                                                                       ['state']),
                                                                                      ('binary',
                                                                                       Pipeline(steps=[('imputer',
                                                                                                        SimpleImputer(strategy='most_frequent')),
                                                                                                       ('BE',
                                                                                                        BinaryEncoder())]),
                                                                                       ['city'])])),
                                                     ('model',
                                                      RandomForestRegressor(max_depth=10,
                                                                            max_features=0.8,
                                                                            n_estimators=400,
                                                                            n_jobs=-1,
                                                                            random_state=42))]))

In [135]:
preds = final_model.predict(x.head(5))

pd.DataFrame({'actual': y.head(5).values, 'predicted': preds.round(0)})

     actual  predicted
0  239900.0   208134.0
1  259900.0   244995.0
2  342500.0   231141.0
3  335000.0   291736.0
4  250000.0   232647.0

In [136]:
print(((df.isnull().sum()/len(df))*100).sort_values(ascending=False))

df['rentestimate'] = df['rentestimate'].fillna(df['rentestimate'].median())
df['lotarea']       = df['lotarea'].fillna(df['lotarea'].median())
df['lot_to_area_ratio'] = df['lotarea'] / df['area']  
df['bathroom']       = df['bathroom'].fillna(df['bathroom'].median())
df['bedroom']        = df['bedroom'].fillna(df['bedroom'].median())
df.to_csv('clean_price_prediction_df.csv', index=False)

rentestimate         26.343896
lotarea               4.916586
lot_to_area_ratio     4.916586
bathroom              0.485480
bedroom               0.061788
city                  0.000000
state                 0.000000
area                  0.000000
latitude              0.000000
longitude             0.000000
listedprice           0.000000
dtype: float64

In [137]:
print(((df.isnull().sum()/len(df))*100).sort_values(ascending=False))

state                0.0
city                 0.0
bedroom              0.0
bathroom             0.0
area                 0.0
lotarea              0.0
rentestimate         0.0
latitude             0.0
longitude            0.0
listedprice          0.0
lot_to_area_ratio    0.0
dtype: float64

In [138]:
import joblib 

joblib.dump(final_model,'house_price_model.pkl')

['house_price_model.pkl']

In [5]:
%%writefile house_price_app.py
import streamlit as st
import pandas as pd
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import joblib
import gzip
import os
import numpy as np

st.set_page_config(page_title=" House Price Analytics", layout="wide")

st.sidebar.title(" House Price Dashboard")

@st.cache_data
def load_data():
    df = pd.read_csv('clean_price_prediction_df.csv')  
    return df

df = load_data()

df['price_per_sqft'] = df['listedprice'] / df['area']
df['lot_to_area_ratio'] = df['lotarea'] / df['area']
df['bed_bath_ratio'] = df['bedroom'] / df['bathroom'].replace(0, np.nan)

page = st.sidebar.radio(
    'Pages',
    ['Main Dashboard', 'Price Factors Analysis', "Prediction"]
)

st.sidebar.title('Filters')

state_filter = st.sidebar.multiselect(
    'State', options=df['state'].unique(), default=df['state'].unique()
)

city_filter = st.sidebar.multiselect(
    'City', options=df['city'].unique(), default=df['city'].unique()
)

filtered_df = df[
    (df['state'].isin(state_filter)) &
    (df['city'].isin(city_filter))
]

if page == "Main Dashboard":
    st.title(" House Price Main Dashboard")
    st.markdown("---")

    col1, col2, col3 = st.columns(3)
    col1.metric(" Avg Listed Price", f"${filtered_df['listedprice'].mean():,.0f}")
    col2.metric(" Avg Area (sqft)", f"{filtered_df['area'].mean():,.0f}")
    col3.metric(" Avg Price/sqft", f"${filtered_df['price_per_sqft'].mean():,.0f}")

    st.subheader("Dataset Preview")
    st.dataframe(filtered_df.head(10))

elif page == "Price Factors Analysis":
    st.title(" Price Factors Analysis")
    tab1, tab2, tab3 = st.tabs(["Size & Rooms", "Location & Market", "Advanced Insights"])

    with tab1:
        st.subheader("Impact of Size & Rooms")
        col1, col2 = st.columns(2)

        with col1:
            fig = px.scatter(filtered_df, x='area', y='listedprice', color='bedroom',opacity=0.6,
                           title='Area vs Price (colored by Bedrooms)',
                           trendline='ols',color_continuous_scale='Viridis')
            st.plotly_chart(fig, use_container_width=True)

        with col2:
            bed_avg = filtered_df.groupby('bedroom')['listedprice'].mean().reset_index()
            fig = px.bar(bed_avg, x='bedroom', y='listedprice',title='Avg Price by Number of Bedrooms',
                color='listedprice',color_continuous_scale='Blues'
            )
        fig.update_layout(coloraxis_showscale=False)
        st.plotly_chart(fig, use_container_width=True)

        
        bath_avg = filtered_df.groupby('bathroom')['listedprice'].mean().reset_index()
        fig = px.bar(bath_avg, x='bathroom', y='listedprice', 
                    title='Avg Price by Bathrooms', color='listedprice',color_continuous_scale='YlGnBu')
        fig.update_traces(width=0.8,textposition='outside')
        fig.update_layout(coloraxis_showscale=False,bargap=0.05,template='plotly_white')
        st.plotly_chart(fig, use_container_width=True)

    with tab2:
        st.subheader("Location & Market Influence")
        col1, col2 = st.columns(2)

        with col1:
            state_price = filtered_df.groupby('state')['listedprice'].mean().sort_values(ascending=False).head(15)
            fig = px.bar(x=state_price.index, y=state_price.values, 
                        title='Avg Price by State (Top 15)', color_discrete_sequence=px.colors.sequential.Plasma,
                labels={'x': 'State', 'y': 'Avg Listed Price'},)
            st.plotly_chart(fig, use_container_width=True)

        with col2:
            fig = px.scatter(
            filtered_df.sample(min(1000, len(filtered_df))),
            x='longitude',y='latitude',color='listedprice',
            size='area',color_continuous_scale=px.colors.sequential.Mint,title='Geographic Distribution of Prices',)
            st.plotly_chart(fig, use_container_width=True)
        
        filtered_df['log_price'] = np.log1p(filtered_df['listedprice'])

        fig = px.histogram(filtered_df,x='log_price',nbins=50,marginal='box',
            title='Log Price Distribution',
            color_discrete_sequence=['#C62828']
        )

        fig.update_layout(title='House Price Distribution',bargap=0.05)
        st.plotly_chart(fig, use_container_width=True)

    with tab3:
        st.subheader("Correlations & Other Factors")
        num_cols = ['bedroom', 'bathroom', 'area', 'lotarea', 'rentestimate', 'price_per_sqft', 'listedprice']
        import plotly.express as px

        corr_price = (
            filtered_df.select_dtypes(include='number')
            .corr()[['listedprice']]
            .sort_values('listedprice', ascending=False)
        )

        fig = px.imshow(corr_price,text_auto='.2f',color_continuous_scale='Reds',
            aspect='auto'
        )

        fig.update_layout(
            title='Correlation with House Price',
            height=600
        )
        st.plotly_chart(fig, use_container_width=True)

        fig = px.scatter(filtered_df, x='rentestimate', y='listedprice', 
                        title='Rent Estimate vs Listed Price', trendline='ols')
        st.plotly_chart(fig, use_container_width=True)
    
elif page == "Prediction":
    st.title('House Price Prediction')

    df = pd.read_csv('clean_price_prediction_df.csv')
    #model = joblib.load('house_price_model.pkl')


    @st.cache_resource
    def load_model():
        model_path = "house_price_model.pkl.gz"
        
        if not os.path.exists(model_path):
            st.error(" Model file not found!")
            st.stop()
        
        try:
            with gzip.open(model_path, 'rb') as f:
                model = joblib.load(f)
            return model
        except Exception as e:
            st.error(f" Error loading model: {str(e)}")
            st.stop()

    
    model = load_model()

    st.dataframe(df.head())

    col1, col2 = st.columns(2)
    with col1:
        state    = st.selectbox('State', sorted(df['state'].dropna().unique()))
        cities   = sorted(df.loc[df['state']==state,'city'].dropna().unique())
        city     = st.selectbox('City', cities)
        bedroom  = st.number_input('Bedrooms', 1, 10, 3)
        bathroom = st.number_input('Bathrooms', 1.0, 10.0, 2.0, step=0.5)
        area     = st.number_input('Area (sq ft)', 200.0, 20000.0, 1800.0)
    with col2:
        lotarea       = st.number_input('Lot Area (acres)', 0.0, 50.0, 0.3)
        rentestimate  = st.number_input('Rent Estimate', 0.0, 20000.0, 1800.0)
        latitude      = st.number_input('Latitude',  -90.0, 90.0,  float(df['latitude'].median()))
        longitude     = st.number_input('Longitude', -180.0, 180.0, float(df['longitude'].median()))

    if st.button('Predict price'):
        lot_ratio = lotarea / area if area else None
        new_row = pd.DataFrame([{
            'state': state, 'city': city,
            'bedroom': bedroom, 'bathroom': bathroom,
            'area': area, 'lotarea': lotarea,
            'rentestimate': rentestimate,
            'latitude': latitude, 'longitude': longitude,
            'lot_to_area_ratio': lot_ratio,
        }])
        pred = model.predict(new_row)[0]
        st.success(f'Predicted listed price: ${pred:,.0f}')

Overwriting house_price_app.py

In [3]:
! streamlit run house_price_app.py

^C

In [2]:
! pip list

Package                   Version
------------------------- -----------
altair                    6.0.0
anyio                     4.12.1
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.1
async-lru                 2.1.0
attrs                     25.4.0
babel                     2.18.0
beautifulsoup4            4.14.3
bleach                    6.3.0
blinker                   1.9.0
cachetools                6.2.6
catboost                  1.2.10
category_encoders         2.9.0
certifi                   2026.1.4
cffi                      2.0.0
charset-normalizer        3.4.4
click                     8.3.1
colorama                  0.4.6
comm                      0.2.3
contourpy                 1.3.3
cycler                    0.12.1
datasist                  1.5.3
debugpy                   1.8.19
decorator                 5.2.1
defusedxml                0.7.1
et_xmlfile                2.0.0
executing                 2.2.1
fastjsonschema            2.21.2
fonttools                 4.62.1
fqdn                      1.5.1
geographiclib             2.1
geopy                     2.4.1
gitdb                     4.0.12
GitPython                 3.1.46
graphviz                  0.21
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.11
imbalanced-learn          0.14.1
ipykernel                 7.2.0
ipython                   9.10.0
ipython_pygments_lexers   1.1.1
ipywidgets                8.1.8
isoduration               20.11.0
jedi                      0.19.2
Jinja2                    3.1.6
joblib                    1.5.3
json5                     0.13.0
jsonpointer               3.0.0
jsonschema                4.26.0
jsonschema-specifications 2025.9.1
jupyter                   1.1.1
jupyter_client            8.8.0
jupyter-console           6.6.3
jupyter_core              5.9.1
jupyter-events            0.12.0
jupyter-lsp               2.3.0
jupyter_server            2.17.0
jupyter_server_terminals  0.5.4
jupyterlab                4.5.4
jupyterlab_pygments       0.3.0
jupyterlab_server         2.28.0
jupyterlab_widgets        3.0.16
kiwisolver                1.5.0
lark                      1.3.1
lightgbm                  4.6.0
MarkupSafe                3.0.3
matplotlib                3.10.9
matplotlib-inline         0.2.1
mistune                   3.2.0
mkl_fft                   2.1.1
mkl_random                1.3.0
mkl-service               2.5.2
narwhals                  2.16.0
nbclient                  0.10.4
nbconvert                 7.17.0
nbformat                  5.10.4
nest_asyncio              1.6.0
nltk                      3.9.4
notebook                  7.5.3
notebook_shim             0.2.4
numpy                     2.4.1
openpyxl                  3.1.5
packaging                 26.0
pandas                    2.3.3
pandocfilters             1.5.1
parso                     0.8.5
patsy                     1.0.2
pillow                    12.1.1
pip                       25.3
platformdirs              4.5.1
plotly                    6.5.2
prometheus_client         0.24.1
prompt_toolkit            3.0.52
protobuf                  6.33.5
psutil                    7.2.1
pure_eval                 0.2.3
pyarrow                   23.0.1
pycountry                 26.2.16
pycparser                 3.0
pydeck                    0.9.1
Pygments                  2.19.2
PyMySQL                   1.1.2
pyparsing                 3.3.2
python-dateutil           2.9.0.post0
python-json-logger        4.0.0
pytz                      2025.2
pywin32                   311
pywinpty                  3.0.3
PyYAML                    6.0.3
pyzmq                     27.1.0
referencing               0.37.0
regex                     2026.4.4
requests                  2.32.5
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rfc3987-syntax            1.1.0
rpds-py                   0.30.0
scikit-learn              1.8.0
scipy                     1.17.0
seaborn                   0.13.2
Send2Trash                2.1.0
setuptools                82.0.0
six                       1.17.0
sklearn-compat            0.1.5
smmap                     5.0.2
soupsieve                 2.8.3
stack_data                0.6.3
statsmodels               0.14.6
streamlit                 1.54.0
tenacity                  9.1.4
terminado                 0.18.1
threadpoolctl             3.6.0
tinycss2                  1.4.0
toml                      0.10.2
tornado                   6.5.4
tqdm                      4.67.3
traitlets                 5.14.3
typing_extensions         4.15.0
tzdata                    2025.3
ua-parser                 1.0.1
ua-parser-builtins        202602
uri-template              1.3.0
urllib3                   2.6.3
user-agents               2.2.0
watchdog                  6.0.0
wcwidth                   0.5.0
webcolors                 25.10.0
webencodings              0.5.1
websocket-client          1.9.0
widgetsnbextension        4.0.15
xgboost                   3.2.0

In [3]:
! pip freeze > requirements.txt

In [4]:
import joblib
import gzip
import shutil
import os


model_path = 'house_price_model.pkl'

with open(model_path, 'rb') as f_in:
    with gzip.open('house_price_model.pkl.gz', 'wb') as f_out:
        shutil.copyfileobj(f_in, f_out)

size_before = os.path.getsize(model_path) / (1024*1024)
size_after = os.path.getsize('house_price_model.pkl.gz') / (1024*1024)

print(f"الحجم قبل الضغط: {size_before:.2f} MB")
print(f"الحجم بعد الضغط: {size_after:.2f} MB")

الحجم قبل الضغط: 33.74 MB
الحجم بعد الضغط: 10.36 MB